export const items = [
  {
    image: "./thumbs/D001-vol.jpg",
    alt: "D001 vol",
    text: "Day 1 Sign Up Page",
    href: "./shows/01-sign-up/index.html",
  },
  {
    image: "./thumbs/D002-ck-out.jpg",
    alt: "D002 ck out",
    text: "Day 2 Check Out Page",
    href: "./shows/02-checkout/index.html",
  },
  {
    image: "./thumbs/D003-landing.jpg",
    alt: "D003 landing",
    text: "Day 3 Landing Page",
    href: "./shows/03-landing/index.html",
  },
  {
    image: "./thumbs/D004-calc.jpg",
    alt: "D004 calc",
    text: "Day 4 Calculator",
    href: "./shows/04-calculator/index.html",
  },
  {
    image: "./thumbs/D005-icon.jpg",
    alt: "D005 icon",
    text: "Day 5 Icon",
    href: "./shows/05-icon/index.html",
  },
  {
    image: "./thumbs/D006-user-profile.jpg",
    alt: "D006 user profile",
    text: "Day 6 User Profile",
    href: "./shows/06-user/index.html",
  },
  {
    image: "./thumbs/D007-settings.jpg",
    alt: "D007 settings",
    text: "Day 7 Settings",
    href: "./shows/07-settings/index.html",
  },
  {
    image: "./thumbs/D008-404-er.jpg",
    alt: "D008 404 er",
    text: "Day 8 404",
    href: "./shows/08-404/index.html",
  },
  {
    image: "./thumbs/D009-music.jpg",
    alt: "D009 music",
    text: "Day 9 Music Player",
    href: "./shows/09-music/index.html",
  },
  {
    image: "./thumbs/D010-social.jpg",
    alt: "D010 social",
    text: "Day 10 Social",
    href: "./shows/10-social/index.html",
  },
  {
    image: "./thumbs/D011-flsh.jpg",
    alt: "D011 flsh",
    text: "Day 11 Flash Message",
    href: "./shows/11-flsh-msg/index.html",
  },
  {
    image: "./thumbs/D012-ecom.jpg",
    alt: "D012 ecom",
    text: "Day 12 E Commerce Shop",
    href: "./shows/12-ecom/index.html",
  },
  {
    image: "./thumbs/D013-dirmsg.jpg",
    alt: "D013 dirmsg",
    text: "Day 13 Direct Messaging",
    href: "./shows/13-dir-msg/index.html",
  },
  {
    image: "./thumbs/D014-countdown.jpg",
    alt: "D014 countdown",
    text: "Day 14 Countdown Timer",
    href: "./shows/14-count-dwn/index.html",
  },
  {
    image: "./thumbs/D015-switch.jpg",
    alt: "D015 switch",
    text: "Day 15 On Off Switch",
    href: "./shows/15-switch/index.html",
  },
  {
    image: "./thumbs/D016-overlay.jpg",
    alt: "D016 overlay",
    text: "Day 16 Pop Up Overlay",
    href: "./shows/16-pop up overlay/index.html",
  },
  {
    image: "./thumbs/D017-receipt.jpg",
    alt: "D017 receipt",
    text: "Day 17 Receipt",
    href: "./shows/17-receipt/index.html",
  },
  {
    image: "./thumbs/D018-chart.jpg",
    alt: "D018 chart",
    text: "Day 18 Analytics Chart",
    href: "./shows/18-analytics chart/index.html",
  },
  {
    image: "./thumbs/D019-leader.jpg",
    alt: "D019 leader",
    text: "Day 19 Leader Board",
    href: "./shows/19-leaderboard/index.html",
  },
  {
    image: "./thumbs/D020-location.jpg",
    alt: "D020 location",
    text: "Day 20 Share Location ?",
    href: "./shows/20-location/index.html",
  },
  {
    image: "./thumbs/D021-home-dash.jpg",
    alt: "D021 home dash",
    text: "Day 21 Home Dashboard",
    href: "./shows/21-home-dash/index.html",
  },
  {
    image: "./thumbs/D022-search.jpg",
    alt: "D022 search",
    text: "Day 22 Search",
    href: "./shows/22-search/index.html",
  },
  {
    image: "./thumbs/D023-onboard.jpg",
    alt: "D023 onboard",
    text: "Day 23 Onboarding",
    href: "./shows/23-onboard/index.html",
  },
  {
    image: "./thumbs/D024-boarding-pass.jpg",
    alt: "D024 boarding pass",
    text: "Day 24 Boarding Pass",
    href: "./shows/24-boarding-pass/index.html",
  },
  {
    image: "./thumbs/D025-TV-app.jpg",
    alt: "D025 TV app",
    text: "Day 25 TV App",
    href: "./shows/25-television/index.html",
  },
  {
    image: "./thumbs/D026-subscribe.jpg",
    alt: "D026 subscribe",
    text: "Day 26 Subscribe",
    href: "./shows/26-subscribe/index.html",
  },
  {
    image: "./thumbs/D027-dropdown.jpg",
    alt: "D027 dropdown",
    text: "Day 27 Expanding Menu",
    href: "./shows/27-dropdown/index.html",
  },
  {
    image: "./thumbs/D028-map-mob.jpg",
    alt: "D028 map mob",
    text: "Day 28 Map",
    href: "./shows/28-map/index.html",
  },
  {
    image: "./thumbs/D029-contact-mob.jpg",
    alt: "D029 contact mob",
    text: "Day 29 Contact Us",
    href: "./shows/29-contact/index.html",
  },
  {
    image: "./thumbs/D030-pricing.jpg",
    alt: "D030 pricing",
    text: "Day 30 Pricing",
    href: "./shows/30-pricing/index.html",
  },
  {
    image: "./thumbs/D031-upload.jpg",
    alt: "D031 upload",
    text: "Day 31 Upload",
    href: "./shows/31-upload/index.html",
  },
  {
    image: "./thumbs/D032-crowd.jpg",
    alt: "D032 crowd",
    text: "Day 32 Crowd Fund",
    href: "./shows/32-crowdfunding/index.html",
  },
  {
    image: "./thumbs/D033-cust-prd.jpg",
    alt: "D033 cust prd",
    text: "Day 33 Customize Product",
    href: "./shows/33-customize/index.html",
  },
  {
    image: "./thumbs/D034-car.jpg",
    alt: "D034 car",
    text: "Day 34 Auto Interface",
    href: "./shows/34-car-inteface/index.html",
  },
  {
    image: "./thumbs/D035-blog.jpg",
    alt: "D035 blog",
    text: "Day 35 Blog",
    href: "./shows/35-blog/index.html",
  },
  {
    image: "./thumbs/D036-offer.jpg",
    alt: "D036 offer",
    text: "Day 36 Special Offer",
    href: "./shows/36-special-offer/index.html",
  },
  {
    image: "./thumbs/D037-weather.jpg",
    alt: "D037 weather",
    text: "Day 37 Weather App",
    href: "./shows/37-weather/index.html",
  },
  {
    image: "./thumbs/D038-calendar.jpg",
    alt: "D038 calendar",
    text: "Day 38 Calendar",
    href: "./shows/38-calendar/index.html",
  },
  {
    image: "./thumbs/D039-testimonial.jpg",
    alt: "D039 testimonial",
    text: "Day 39 Testimonial",
    href: "./shows/39-testimonial/index.html",
  },
  {
    image: "./thumbs/D040-recipe.jpg",
    alt: "D040 recipe",
    text: "Day 40 Recipe",
    href: "./shows/40-recipe/index.html",
  },
  {
    image: "./thumbs/D041-exercise.jpg",
    alt: "D041 exercise",
    text: "Day 41 Work Out App",
    href: "./shows/41-exercise/index.html",
  },
  {
    image: "./thumbs/D042-todo.jpg",
    alt: "D042 todo",
    text: "Day 42 ToDo",
    href: "./shows/42-todo/index.html",
  },
  {
    image: "./thumbs/D043-menu.jpg",
    alt: "D043 menu",
    text: "Day 43 Food Menu",
    href: "./shows/43-food-menu/index.html",
  },
  {
    image: "./thumbs/D044-favs.jpg",
    alt: "D044 favs",
    text: "Day 44 Favorites",
    href: "./shows/44-favorites/index.html",
  },
  {
    image: "./thumbs/D045-info.jpg",
    alt: "D045 info",
    text: "Day 45 Information Card",
    href: "./shows/45-info-card/index.html",
  },
  {
    image: "./thumbs/D046-invoice.jpg",
    alt: "D046 invoice",
    text: "Day 46 Invoice",
    href: "./shows/46-invoice/index.html",
  },
  {
    image: "./thumbs/D047-activity.jpg",
    alt: "D047 activity",
    text: "Day 47 Activity Feed",
    href: "./shows/47-activity-feed/index.html",
  },
  {
    image: "./thumbs/D048-soon.jpg",
    alt: "D048 soon",
    text: "Day 48 Coming Soon",
    href: "./shows/48-coming-soon/index.html",
  },
  {
    image: "./thumbs/D049-notification.jpg",
    alt: "D049 notification",
    text: "Day 49 Notification",
    href: "./shows/49-notification/index.html",
  },
  {
    image: "./thumbs/D050-job.jpg",
    alt: "D050 job",
    text: "Day 50 Job Listing",
    href: "./shows/50-job/index.html",
  },
  {
    image: "./thumbs/D051-press-page.jpg",
    alt: "D051 press page",
    text: "Day 51 Press Page",
    href: "./shows/51-press-page/index.html",
  },
  {
    image: "./thumbs/D052-logo-design.jpg",
    alt: "D052 logo design",
    text: "Day 52 Logo Design",
    href: "./shows/52-logo/index.html",
  },
  {
    image: "./thumbs/D053-nav-bar.jpg",
    alt: "D053 nav bar",
    text: "Day 53 Navigation Bar",
    href: "./shows/53-navigation/index.html",
  },
  {
    image: "./thumbs/D054-confirm.jpg",
    alt: "D054 confirm",
    text: "Day 54 Confirmation Page",
    href: "./shows/54-confirmation/index.html",
  },
  {
    image: "./thumbs/D055-icon-set.jpg",
    alt: "D055 icon set",
    text: "Day 55 Icon Set",
    href: "./shows/55-icon-set/index.html",
  },
  {
    image: "./thumbs/D056-breadcrumbs.jpg",
    alt: "D056 breadcrumbs",
    text: "Day 56 Breadcrumb Navigation",
    href: "./shows/56-breadcrumbs/index.html",
  },
  {
    image: "./thumbs/D057-video-player.jpg",
    alt: "D057 video player",
    text: "Day 57 Video Player",
    href: "./shows/57-video-player/index.html",
  },
  {
    image: "./thumbs/D058-shopping-cart.jpg",
    alt: "D058 shopping cart",
    text: "Day 58 Shopping Cart",
    href: "./shows/58-shopping-cart/index.html",
  },
  {
    image: "./thumbs/D059-background.jpg",
    alt: "D059 background",
    text: "Day 59 Background",
    href: "./shows/59-background/index.html",
  },
  {
    image: "./thumbs/D060-color-picker.jpg",
    alt: "D060 color picker",
    text: "Day 60 Color Picker",
    href: "./shows/60-color-picker/index.html",
  },
  {
    image: "./thumbs/D061-redeem-cupon.jpg",
    alt: "D061 redeem cupon",
    text: "Day 61 Redeem Coupon",
    href: "./shows/61-redeem-coupon/index.html",
  },
  {
    image: "./thumbs/D062-workout.jpg",
    alt: "D062 workout",
    text: "Day 62 Work Out Of The Day",
    href: "./shows/62-workout-of-day/index.html",
  },
  {
    image: "./thumbs/D063-best-of.jpg",
    alt: "D063 best of",
    text: "Day 63 Best Of",
    href: "./shows/63-best-of/index.html",
  },
  {
    image: "./thumbs/D064-use-select.jpg",
    alt: "D064 use select",
    text: "Day 64 User Select",
    href: "./shows/64-user-selection/index.html",
  },
  {
    image: "./thumbs/D065-notes.jpg",
    alt: "D065 notes",
    text: "Day 65 Notes",
    href: "./shows/65-notes/index.html",
  },
  {
    image: "./thumbs/D066-statistics.jpg",
    alt: "D066 statistics",
    text: "Day 66 Sunburst Statistics",
    href: "./shows/66-statistics/index.html",
  },
  {
    image: "./thumbs/D067-home-rental.jpg",
    alt: "D067 home rental",
    text: "Day 67 Home Rental",
    href: "./shows/67-home-rental/index.html",
  },
  {
    image: "./thumbs/D068-flight-search.jpg",
    alt: "D068 flight search",
    text: "Day 68 Flight search",
    href: "./shows/68-flight-search/index.html",
  },
  {
    image: "./thumbs/D069-trending.jpg",
    alt: "D069 trending",
    text: "Day 69 Trending",
    href: "./shows/69-trending/index.html",
  },
  {
    image: "./thumbs/D070-event.jpg",
    alt: "D070 event",
    text: "Day 70 Event Listing",
    href: "./shows/70-event-list/index.html",
  },
  {
    image: "./thumbs/D071-schedling.jpg",
    alt: "D071 schedling",
    text: "Day 71 Scheduling App",
    href: "./shows/71-scheduling/index.html",
  },
  {
    image: "./thumbs/D072-carousel-sldier.jpg",
    alt: "D072 carousel sldier",
    text: "Day 72 Carousel",
    href: "./shows/72-carousel/index.html",
  },
  {
    image: "./thumbs/D072-slide-mouseover.jpg",
    alt: "D072 slide mouseover",
    text: "Day 72 Carousel",
    href: "./shows/72-carousel/index.html",
  },
  {
    image: "./thumbs/D073-vr.jpg",
    alt: "D073 vr",
    text: "Day 73 Virtual Reality",
    href: "./shows/73-vr/index.html",
  },
  {
    image: "./thumbs/D074-download.jpg",
    alt: "D074 download",
    text: "Day 74 Download",
    href: "./shows/74-download/index.html",
  },
  {
    image: "./thumbs/D075-pre-ord.jpg",
    alt: "D075 pre ord",
    text: "Day 75 Pre Order",
    href: "./shows/75-pre-ord/index.html",
  },
  {
    image: "./thumbs/D076-load-snowman.jpg",
    alt: "D076 load snowman",
    text: "Day 76 Loading",
    href: "./shows/76-load-snow/index.html",
  },
  {
    image: "./thumbs/D076-loading.jpg",
    alt: "D076 loading",
    text: "Day 76 Loading",
    href: "./shows/76-load-snow/index.html",
  },
  {
    image: "./thumbs/D077-thankyou.jpg",
    alt: "D077 thankyou",
    text: "Day 77 Thank You",
    href: "./shows/77-thankyou/index.html",
  },
  {
    image: "./thumbs/D078-invitation.jpg",
    alt: "D078 invitation",
    text: "Day 78 Invitation",
    href: "./shows/78-invitation/index.html",
  },
  {
    image: "./thumbs/D079-itinerary-mobile.jpg",
    alt: "D079 itinerary mobile",
    text: "Day 79 Itinerary",
    href: "./shows/79-itinerary/index.html",
  },
  {
    image: "./thumbs/D079-itinerary.jpg",
    alt: "D079 itinerary",
    text: "Day 79 Itinerary",
    href: "./shows/79-itinerary/index.html",
  },
  {
    image: "./thumbs/D080-date-picker.jpg",
    alt: "D080 date picker",
    text: "Day 80 Date Picker",
    href: "./shows/80-date-picker/index.html",
  },
  {
    image: "./thumbs/D081-status-update.jpg",
    alt: "D081 status update",
    text: "Day 81 HTTP Status Update",
    href: "./shows/81-status-update/index.html",
  },
  {
    image: "./thumbs/D082-forms.jpg",
    alt: "D082 forms",
    text: "Day 82 Form",
    href: "./shows/82-forms/index.html",
  },
  {
    image: "./thumbs/D083-button.jpg",
    alt: "D083 button",
    text: "Day 83 Button",
    href: "./shows/83-button/index.html",
  },
  {
    image: "./thumbs/D084-badge.jpg",
    alt: "D084 badge",
    text: "Day 84 Badges",
    href: "./shows/84-badge/index.html",
  },
  {
    image: "./thumbs/D085-pagination.jpg",
    alt: "D085 pagination",
    text: "Day 85 Pagination",
    href: "./shows/85-pagination/index.html",
  },
  {
    image: "./thumbs/D086-progress.jpg",
    alt: "D086 progress",
    text: "Day 86 Progress",
    href: "./shows/86-progress/index.html",
  },
  {
    image: "./thumbs/D087-tooltip.jpg",
    alt: "D087 tooltip",
    text: "Day 87 Tooltip",
    href: "./shows/87-tooltip/index.html",
  },
  {
    image: "./thumbs/D088-avatar.jpg",
    alt: "D088 avatar",
    text: "Day 88 Avatar",
    href: "./shows/88-avatar/index.html",
  },
  {
    image: "./thumbs/D089-agree.jpg",
    alt: "D089 agree",
    text: "Day 89 Agree to Terms",
    href: "./shows/89-agree/index.html",
  },
  {
    image: "./thumbs/D090-create-new.jpg",
    alt: "D090 create new",
    text: "Day 90 Create New",
    href: "./shows/90-create/index.html",
  },
  {
    image: "./thumbs/D091-curated.jpg",
    alt: "D091 curated",
    text: "Day 91 Curated",
    href: "./shows/91-curated/index.html",
  },
  {
    image: "./thumbs/D092-faq.jpg",
    alt: "D092 faq",
    text: "Day 92 FAQ",
    href: "./shows/92-faq/index.html",
  },
  {
    image: "./thumbs/D093-splash.jpg",
    alt: "D093 splash",
    text: "Day 93 Splash Screen",
    href: "./shows/93-splash/index.html",
  },
  {
    image: "./thumbs/D094-news.jpg",
    alt: "D094 news",
    text: "Day 94 News Reader",
    href: "./shows/94-news/index.html",
  },
  {
    image: "./thumbs/D095-product-tour.jpg",
    alt: "D095 product tour",
    text: "Day 95 Product Tour",
    href: "./shows/95-product-tour/index.html",
  },
  {
    image: "./thumbs/D096-in-stock.jpg",
    alt: "D096 in stock",
    text: "Day 96 In Stock",
    href: "./shows/96-in-stock/index.html",
  },
  {
    image: "./thumbs/D097-giveaway.jpg",
    alt: "D097 giveaway",
    text: "Day 97 Giveaway",
    href: "./shows/97-giveaway/index.html",
  },
  {
    image: "./thumbs/D098-ad.jpg",
    alt: "D098 ad",
    text: "Day 98 Ad",
    href: "./shows/98-advertisement/index.html",
  },
  {
    image: "./thumbs/D099-categories-side.jpg",
    alt: "D099 categories side",
    text: "Day 99 Categories",
    href: "./shows/99-categories/index.html",
  },
  {
    image: "./thumbs/D100-multi-level-categories.jpg",
    alt: "D100 multi level categories",
    text: "Day 100 Multi Level Side Bar",
    href: "./shows/100-multi-level-sidebar/index.html",
  },
  {
    image: "./thumbs/D101-flt-search-mob.jpg",
    alt: "D101 flt search mob",
    text: "Day 101 Mobile Flight Search",
    href: "./shows/101-mobile-flight-search/index.html",
  },
  {
    image: "./thumbs/D102-quote.jpg",
    alt: "D102 quote",
    text: "Day 102 Quote",
    href: "./shows/102-quote/index.html",
  },
];
